### ISSUE TITLE
Wallpaper stretches on dual screen

### ISSUE THREAD

**Issue by Niroj11** [adi1090x/battery-wallpaper#10]
OS: Linux Mint 19

The wallpaper stretches when using dual screen mode. I think it will be best if you split the same wallpaper onto dual screen.

**Comment by adi1090x** [comment]
Sorry, i don't have dual monitor & never used before so, can't fix it.
But if you or someone can fix it, PR pls.

**Comment by adi1090x** [comment]
Fixed it, try again.
