### ISSUE TITLE
In Mac OS Catalina, wallpapers blink

### ISSUE THREAD

**Issue by smnfs** [adi1090x/battery-wallpaper#13]
macos-wallpaper is installed via brew.
setting wallpapers with it works like a charm.

But battery-wallpaper sets an image and ~5s later it blinks to the default Catalina Wallpaper and back
(before using battery-wallpaper I didn't even have the Catalina Wallpaper set.)
Seems to be some Mac or maybe Catalina specific problem

Any ideas?

**Comment by adi1090x** [comment]
Sorry... NO Idea, i don't have a mac.
