### ISSUE TITLE
Wallpaper not changing

### ISSUE THREAD

**Issue by dhiyo7** [adi1090x/battery-wallpaper#19]
I used ZorinOS
![dev7@007:~-Project-PLUGIN-battery-wallpaper-images_530](https://user-images.githubusercontent.com/25566307/109708397-f262b780-7bcd-11eb-9c82-7b028a0de84d.png)

**Nothing Change**
![Workspace 1_531](https://user-images.githubusercontent.com/25566307/109708517-1625fd80-7bce-11eb-9489-3215750add73.png)

**Comment by adi1090x** [comment]
Not tested on Zorin, Might not work.
