### ISSUE TITLE
Wallpaper not changing

### ISSUE THREAD

**Issue by paulhewson** [adi1090x/battery-wallpaper#20]
Hi, `echo $DESKTOP_SESSION` returns `ubuntu-wayland`
I'm currently on Ubuntu 20.04 LTS
Thank you for your support

**Comment by JuanU2** [comment]
> 

Hello. I had the same issue, and I solved it pressing `Alt + F2` and running `gnome-session-properties` command. Then I pressed `Add` and in the `Command` field I added `nohup bwall -d 1 -s cup_dark &`   of course you can change your wallpaper preference. Then I pressed `Add` to confirm. It worked for me. Lmk if something is not right.
